### PR TITLE
Multinode

### PR DESCRIPTION
**Pull request by ckhmer1**
Hi,
this is a multi traits node,
It doesn't support all nodes yet but is just for a start.
So it is still a work in progress...

### CODE REVIEW

**Comment by homefefeld** [comment]
I'm going to test this asap !!!!!

**Comment by Aragur** [comment]
Hey just out of curiosity why should a multi node be useful?

**Comment by ckhmer1** [comment]
Hi,
If you have a fan with light and rotation control.
If you have a bed that can be warm or cold.
If you have a hood with light, modes.
Because also Google allows mixing traits in order to better match your devices.
Who are us to limit the fantasy?

**Comment by homefefeld** [comment]
This node (multi-node, again should be called generic-node.. 😄 ) is so usefull, you can add the traits you really want to your device. you can really personalise your device and display it on Nest-Hub !!! obvioulsy you need to understand what your are doing when using it. but isn't it for most of red-node stuff ?

**Pull request merged**
