### PR TITLE
Improve node-RED contrib node compliance

### PR DESCRIPTION
**Pull request by Paul-Reed**
node-RED has introduced a quality check (scoreboard rating) to indicate that contrib nodes are reaching the minimum specs expected by the node-RED team.
I added an example flow previously (1 point when the depreciated nodes have been removed), and these two additions will improve the SH score by a further 2 points.
See https://discourse.nodered.org/t/introducing-node-scorecards-and-a-new-node-naming-convention/57559/28

For consideration...

### CODE REVIEW

**Comment by ckhmer1** [comment]
Hi Paul,
forcing to use node version 12 or upper prevent to install the google smart home on several OS.
For example, the latest LTS Ubuntu version is using node v10.19.0.
My suggestion is to set the minimum requirement to v10.0.0.
I know that several node packages are setting the minimum request to v12.0.0, in my opinion, it is a version too new to set as a minimum requirement.
What do You think about it?

**Comment by Paul-Reed** [comment]
It is a node-RED package requirement for a minimum node version 12, for all NR versions >= v2.0.0, and only NR versions v1.3.7 and below will accept node v10.

Also, we could not then specify a minimum node-RED version >=2.0.0 (as that needs node v12), so we would also be required to set back to NR >=1.3.0

Of course, its not all about the scoring system, but SH would then fail both of those hurdles.

I assume there is no reason why Ubuntu users couldn't update their node version?
It seemed an opportune time to introduce minimum standards as a Major version change is about to be introduced (by removing nodes), and it's a good opportunity for users to also bring their systems up to date.

However, it's up to @ckhmer1 & @Caprico85 , and I'll gladly change it to whatever versions they think appropriate, or just close the PR.

**Comment by ckhmer1** [comment]
Sorry,
You are right, I didn't check the Node-RED EOL.

**Comment by Caprico85** [comment]
Do we have to set a version of Node-RED >= 2.0.0? Setting it to >= 1.3.0 and node to >= 10 should satisfy the scoreboard, while still allowing newer versions of Node-RED and node.

On the other hand, I don't really have a big problem with raising the dependencies. Yes, Ubuntu LTS (20.04) still ships with node v10. Good if we can satisfy this. But I see no problem if not. Node v10 is already EOL, Ubuntu 20.04 will be EOL in 2-3 months. Everybody who is able to setup node-red-contrib-google-smarthome should also be able add an apt apt repository with updated node.js.

**Comment by Paul-Reed** [comment]
The wording in the node-RED release information about the scoreboard is ambiguous, but looking at some other nodes that have now successfully passed the threshold, seem to use;
`node-RED >=1.3.7`
`node >= 10.0.0`
So yes, apologies, I stand corrected.

I'll update the PR.

**Comment by Caprico85** [comment]
Released v0.2.9 including this PR. All version checks [on the scorecard](https://flows.nodered.org/node/node-red-contrib-google-smarthome/scorecard) green now. Great work 👍

**Comment by Paul-Reed** [comment]
Hopefully, when the depreciated nodes are removed, you should gain another point.
But I'm not convinced that fewer dependencies make a better contrib node!!

**Pull request merged**
