### PR TITLE
Add error message for wrong username/password (fixes #15)

### LINKED ISSUE #15: No error message on wrong username/password
You only get a blank, grey screen without an error message if you enter the wrong username/password during account linking.

See #14.

### PR DESCRIPTION
**Pull request by Caprico85**
Simplified the login page and added an error message if you enter wrong username/password.

### CODE REVIEW

**Comment by mikejac** [comment]
@Caprico85: I take it you have tested this thoroughly, yes?

**Comment by Caprico85** [comment]
Yes. Tested on 2 different installations. Works with correct password on the first try and with one ore multiple rounds of incorrect passwords before entering the right one. Login page still looks almost the same as before.

I noticed there is an issue when you unlink and try to relink your account. Sometimes relinking doesn't work until you delete the auth storage. But thats a different topic and also happens without my changes.

If you prefer to keep the html framework I guess that can be done too. But I think it is a bit too much to have 1500 files just for one simple login page.

**Comment by Caprico85** [comment]
Updated my pull request to add a small animation to the error message on page load. This makes it easier to notice that the page was submitted and your password is still wrong. Usually the page reloads so fast you could think the submit button did not do anything at all.

**Comment by mikejac** [comment]
Published to npm.

**Pull request merged**
