### PR TITLE
set_state message

### PR DESCRIPTION
**Pull request by ckhmer1**
Hi,
the patch allows the management node to send a set_state message if a device state change (after some delay). 

This message can be persisted if needed and can be passed into the management node to restore the persisted state.

There are the following two timers:

- after 10 seconds of a node deployment, request sync is sent to Google in order to align all the devices' properties. 
- after 30 seconds of a state update (state change), a "set_state" message is sent to the management node output to allow the save the new state.

I'm not sure if I should insert those timers' duration in the configuration GUI?

Thanks

### CODE REVIEW

**Comment by Caprico85** [comment]
> I'm not sure if I should insert those timers' duration in the configuration GUI?

I wouldn't. Configuration is already hard enough for users. And I can't think of a reason why a normal user wants to change these values.

**Comment by Paul-Reed** [comment]
I agree with @Caprico85 
However... is this a setting that could possible be included in a 'Advanced Options' config setting which is by default hidden?
For example see [node-red-contrib-ui-level](https://flows.nodered.org/node/node-red-contrib-ui-level) whose config settings expand (user hotnipi is very helpful with this feature)

**Comment by ckhmer1** [comment]
I'd a quick look at the node-red-contriv-ui.level GUI but I didn't find the expanding section.

Anyway, also the Google config GUI has sections expanding based on the user configuration.

I could create a new Section "Advanced settings" which include the actual config "Report Interval (m)" and the new two configs:

1. Delay for request sync after a deploy
2. Delay for sending the set_state message after state changes

What do You think about it?

**Comment by Paul-Reed** [comment]
> I'd a quick look at the node-red-contrib-ui-level GUI but I didn't find the expanding section.

I was suggesting replacing the drop down in the example below with a tick box (Advanced options) to make the options easier to access for users, but please progress as you wish. You've done a great job so far, and we do appreciate all the time & effort that you are making.

options

**Comment by ckhmer1** [comment]
Hi,
I've added the advanced settings section just for the two parameters above.

I've also found a way to unregister the Node-RED HTTP endpoints, I hope this fixed issue  #174 .

I've also added a check for the content of httpNodeRoot see [Configuration](https://nodered.org/docs/user-guide/runtime/configuration):

httpNodeRoot: the root url for nodes that provide HTTP endpoints. **If set to false, all node-based HTTP endpoints are disabled**. 

Claudio

**Comment by ckhmer1** [comment]
Hi,
there is also the fix for issue #184 

Claudio

**Comment by Paul-Reed** [comment]
This latest introduces a node error warning when updating, see the red triangle;

error
;

If I look in Advanced settings, note that `Request sync delay` & `Set state message delay` are edged red, and have no default values;

advsettings

Manually adding the default values resolves the issue;

resolved

**Comment by brianmay** [comment]
I am not sure if this is related or not, but since applying this change my connection to Google seems to be failing after X minutes, with the following error being displayed in node-red:

```
HttpActions:httpActionsRegister(/smarthome): no accessToken found
```

If I redeploy or something (not sure what yet), then it starts working again.

**Pull request merged**
