### PR TITLE
Create dimmable light example

### PR DESCRIPTION
**Pull request by Paul-Reed**
As described in https://github.com/mikejac/node-red-contrib-google-smarthome/issues/216
This is a simple example flow for a dimmable light using the device node

### CODE REVIEW

**Comment by FireWizard52** [comment]
Hello @Paul-Reed,

A very good initiative, so that simple questions not end up in github issues.

I copied your example and I discovered something, that I also saw yesterday evening late at one of my configurations.
The device works fine and gives the correct output if operated from the Google Home app or (not tested) by voice.
However if we look to the Inject nodes and activate these everything is correct indicated under the Google device node,
except, if the "Command/Query" has been set to "Command only On/Off".

In this case ON or OFF is not indicated, while bri:25 or bri:100 is indicated.
I don"t see any reason why ON or OFF is omitted.  I think this is a bug.

Regards

**Comment by Paul-Reed** [comment]
Added example to query temperature & humidity sensor data

**Comment by Caprico85** [comment]
Great work!

Just one suggestion. I usually leave the smarthome config unselected in my example flows.

image

While being technically invalid, the flow can still be exported. The user has to open the node and select their own config anyway. By not including our config we remind the users to choose their config. And we don't clutter the users Node-RED with our imported but unused configs.

**Comment by Paul-Reed** [comment]
Good point!
I'll update the PR shortly.

**Comment by Paul-Reed** [comment]
They have now been updated.

**Comment by Caprico85** [comment]
Thank you!

**Pull request merged**
