### PR TITLE
Bug fix

### PR DESCRIPTION
**Pull request by ckhmer1**
If a device is offline return the error deviceOffline.
Uses the internal formatValue

### CODE REVIEW

**Comment by Paul-Reed** [comment]
Just applied your PR @ckhmer1 as a diff, and noticed that I get;
```
modifyUpdateMessage Basisklasse: {"device_name":"garden light","command":"OnOff","params":{"on":true},"payload":{"online":true,"on":true},"topic":"shellies/gjd-controller/relay/0/command"}
POST /smarthome 200 24.645 ms - 144
modifyUpdateMessage Basisklasse: {"device_name":"garden light","command":"OnOff","params":{"on":false},"payload":{"online":true,"on":false},"topic":"shellies/gjd-controller/relay/0/command"}
POST /smarthome 200 7.176 ms - 144
```

If I remove your patch, I get;
```
modifyUpdateMessage Basisklasse: {"device_name":"garden light","command":"OnOff","params":{"on":true},"payload":{"online":true,"on":true},"topic":"shellies/gjd-controller/relay/0/command"}
POST /local_smarthome 200 41.298 ms - 144
modifyUpdateMessage Basisklasse: {"device_name":"garden light","command":"OnOff","params":{"on":false},"payload":{"online":true,"on":false},"topic":"shellies/gjd-controller/relay/0/command"}
POST /local_smarthome 200 21.379 ms - 144
```
Tried 3 times, and the results are repeatable.

**Comment by Chrischi-** [comment]
@Paul-Reed 
> ```
> modifyUpdateMessage Basisklasse: {"device_name":"garden light","command":"OnOff","params":{"on":true},"payload":{"online":true,"on":true},"topic":"shellies/gjd-controller/relay/0/command"}
> POST /smarthome 200 24.645 ms - 144
> modifyUpdateMessage Basisklasse: {"device_name":"garden light","command":"OnOff","params":{"on":false},"payload":{"online":true,"on":false},"topic":"shellies/gjd-controller/relay/0/command"}
> POST /smarthome 200 7.176 ms - 144
> ```
> 
> ```
> modifyUpdateMessage Basisklasse: {"device_name":"garden light","command":"OnOff","params":{"on":true},"payload":{"online":true,"on":true},"topic":"shellies/gjd-controller/relay/0/command"}
> POST /local_smarthome 200 41.298 ms - 144
> modifyUpdateMessage Basisklasse: {"device_name":"garden light","command":"OnOff","params":{"on":false},"payload":{"online":true,"on":false},"topic":"shellies/gjd-controller/relay/0/command"}
> POST /local_smarthome 200 21.379 ms - 144
> ```

Why are your local executions slower than those via cloud?

**Comment by ckhmer1** [comment]
> Just applied your PR @ckhmer1 as a diff, and noticed that I get;
> 
> ```
> modifyUpdateMessage Basisklasse: {"device_name":"garden light","command":"OnOff","params":{"on":true},"payload":{"online":true,"on":true},"topic":"shellies/gjd-controller/relay/0/command"}
> POST /smarthome 200 24.645 ms - 144
> modifyUpdateMessage Basisklasse: {"device_name":"garden light","command":"OnOff","params":{"on":false},"payload":{"online":true,"on":false},"topic":"shellies/gjd-controller/relay/0/command"}
> POST /smarthome 200 7.176 ms - 144
> ```
> 
> If I remove your patch, I get;
> 
> ```
> modifyUpdateMessage Basisklasse: {"device_name":"garden light","command":"OnOff","params":{"on":true},"payload":{"online":true,"on":true},"topic":"shellies/gjd-controller/relay/0/command"}
> POST /local_smarthome 200 41.298 ms - 144
> modifyUpdateMessage Basisklasse: {"device_name":"garden light","command":"OnOff","params":{"on":false},"payload":{"online":true,"on":false},"topic":"shellies/gjd-controller/relay/0/command"}
> POST /local_smarthome 200 21.379 ms - 144
> ```
> 
> Tried 3 times, and the results are repeatable.

I'm not sure what You are trying to explain.

With this PR the local execution doesn't work anymore?

**Comment by Paul-Reed** [comment]
Hi Claudio.
> With this PR the local execution doesn't work anymore?

Yes, that's correct, I tried and reverted the diff 3 times and on each occasion local execution did not work when the diff was applied, and it reverted to cloud execution.
It's strange, because I've just returned home again, and now Local Execution is **working fine with the patch applied**. So can't explain.... sorry.

> Why are your local executions slower than those via cloud?

It's probably because I was rebooting my Pi between applying & removing the diff, which slowed down execution time on that occasion.
It usually takes between 7 & 10 ms for Local Executions, does that time sound acceptable?

**Comment by Caprico85** [comment]
I also don't have problems with local fulfillment after applying this patch. It probably only took some time for local fulfillment to rediscover devices.

> It usually takes between 7 & 10 ms for Local Executions, does that time sound acceptable?

15 to 20 ms here. But this is only the time spent by Node-RED to handle the request. It's totally normal for local and classic requests to take roughly the same time inside Node-RED. The main performance benefit for local execution is that it reduces network communication between Google servers, smart speaker and Node-RED. Less network communication means less time spent waiting for network roundtrips. This is something you cannot measure inside Node-RED.

**Comment by Paul-Reed** [comment]
Thanks @Caprico85, that's reassuring.
In practice, it certainly seems faster than I remember with cloud execution.
One quick question... do you know why my node-RED log is filled up with log entries occurring every minute or so?
```
POST /local_smarthome 200 8.034 ms - 414
POST /local_smarthome 200 8.716 ms - 414
POST /local_smarthome 200 8.146 ms - 414
POST /local_smarthome 200 8.820 ms - 414
POST /local_smarthome 200 8.298 ms - 414
POST /local_smarthome 200 8.332 ms - 414
POST /local_smarthome 200 8.742 ms - 414
POST /local_smarthome 200 9.244 ms - 414
POST /local_smarthome 200 8.742 ms - 414
POST /local_smarthome 200 8.680 ms - 414
POST /local_smarthome 200 8.362 ms - 414
POST /local_smarthome 200 8.787 ms - 414
POST /local_smarthome 200 8.751 ms - 414
```

**Pull request merged**
