### PR TITLE
Local Fulfillment udp config

### PR DESCRIPTION
**Pull request by ckhmer1**
This PR allows to use the UDP config for the local fulfillment.
In this way, it is possible to use inside the container.

My docker container receive the UDP message, the device inspect has no error, and this morning the local fulfillment is  working for me.

Someone could test it with both configurations (UDP and MDNS)?

Thanks
Claudio

### CODE REVIEW

**Comment by Caprico85** [comment]
I'm making progress.

Finally I got the The REACHABLE_DEVICES intent to work. I'm seeing no errors in chrome://inspect anymore. Unfortunately Google still doesn't let me control my devices via local execution. I'm not getting the ring icon and I cant control my devices after saying "Hey Google, force local". Google seems to not even try local exection and always uses normal exection. I'll investigate further.

It took me quite some time to find out the discovery packet is specified. In the Google Console it is hex encoded, in Node-RED it is plain text. I think we should change this. The packet in Node-RED should at least be hex encoded too, so the discovery packets in Console and Node-RED are identical.

Actually, I would not even make the packet configurable in Node-RED. I can't think of a reason why the user would want to change it. Having the packet configurable confuses the user and leaves room for mistakes (which in turn leads to bug reports). Instead I would rather use a hard-coded string like "node-red-contrib-google-smarthome". Then explain in the setup instructions to enter "6e6f64652d7265642d636f6e747269622d676f6f676c652d736d617274686f6d65" (hex equivalent of this string) in the Google Console.

**Comment by ckhmer1** [comment]
Thanks for testing.
Did You test also the mDNS configuration?
I'll perform the changes for the scan packet.

**Comment by Caprico85** [comment]
I tried it now on my second install at my parents flat. Here it works without problems.

Still can't get it to work on my first install. Neither with mDNS nor UDP scanning, reverting to an unmodified v0.3.14 does not help either. REACHABLE_DEVICES always works, but Google never uses the local path. It's probably some of Google's oddities where you absolutely can't get it to work and a week later it magically starts to work. It does not seems to be related to your changes.

Therefore: Merged. Thank you!

**Comment by ckhmer1** [comment]
Hi,
Good news, thanks for testing.

**Comment by ckhmer1** [comment]
Hi Caprico,
when do You deliver this PR? It contains some bug fix too.

Thanks
Claudio

**Comment by Caprico85** [comment]
Released as 0.4.0

I was busy updating the docs to have all changes related to UDP scanning. Docs still mostly referred to MDNS scanning only.

This release is backwards incompatible, Local fulfillment defaults to being disabled after update. It will break local fulfillment for all users until they select MDNS scanning in the config. As some users will look at the docs to get local fulfillment working again, I wanted to have the docs updated before doing the release.

**Comment by ckhmer1** [comment]
Thanks

**Pull request merged**
