### PR TITLE
Use Credentials

### PR DESCRIPTION
**Pull request by ckhmer1**
Hi,
with this update, the node uses the credentials mechanism to store the following info:

* loginclientid
* emails
* username
* password
* publickey
* privatekey
* jwtkey
* clientid
* clientsecret

This prevents including that information during the export operation.

Ciao
Claudio

### CODE REVIEW

**Comment by Caprico85** [comment]
Did you find a way to migrate the user's data from the old non-credential fields to the new credential fields? Or do users have to re-enter their data? I trief the same a while ago and didn't find a way (#26).

**Comment by ckhmer1** [comment]
Hi,
I didn't try to migrate the credentials, the user should enter the credential again.
I'll try to investigate this problem.

Thanks
Claudio

**Comment by Caprico85** [comment]
Don't put to much time in it. I tried the same for #26 and didn't found a solution. I tried different ways. Depending on where you put the logic, you can not access old and new fields in parallel. Or you can access both fields, but you can't clear settings for the old fields, so the old fields would still exist, still contain you userdata.

If there is no simple solution, I think I will merge this PR anyways. I prefer the "clean" way, without having to use hacks to migrate credentials. If this means the user will have to re-enter the credentials, then so be it. I mean, we are still in beta. Breaking changes like this should be expected 😀.

**Comment by Paul-Reed** [comment]
I've simply highlighted the Smarthome Management node, and then exported the node, saving it as text. The export seems to contain all of the credentials which will be required to paste in the updated node.
(which is of course why you are moving to the 'credential' model)

**Comment by Caprico85** [comment]
I added a note to the Readme and the release notes about having to reenter the credentials and released v0.1.0.

**Pull request merged**
